Update help window
AY2324S2-CS2103T-W09-3/tp pull request #35
Opened 2024-03-16 15:11 UTC by KSSWSept20

- Add a command summary table to the help window.
- Enable user to close the window easily by typing 'q'.

2024-03-17 04:31 UTC, Tanzhiheng26 requested changes
Help window looks good, just a few nits to fix.

2024-03-17 04:31 UTC, Tanzhiheng26 commented on src/main/java/seedu/address/ui/HelpWindow.java
> +                + "Can also call by typing F1 on keyboard"));
```suggestion
        guideItems.add(new UserGuideItem("help", "Open command summary (can also be accessed by pressing F1 key)"));
```

2024-03-17 04:31 UTC, Tanzhiheng26 commented on src/main/java/seedu/address/ui/HelpWindow.java
> +            + "\n  • Close this window by typing 'q' on keyboard.";
```suggestion
            + "\n  • Press 'q' to close this window.";
```

2024-03-17 04:31 UTC, Tanzhiheng26 commented on docs/UserGuide.md
> +Closes the help window by typing 'q' on keyboard.
```suggestion
Press 'q' to close the help window.
```

2024-03-17 04:31 UTC, Tanzhiheng26 commented on src/main/java/seedu/address/ui/HelpWindow.java
> +                + "e.g., filter supplier"));
```suggestion
                + "e.g., filter supplier seafood"));
```

2024-03-17 04:31 UTC, Tanzhiheng26 commented on src/main/java/seedu/address/ui/HelpWindow.java
> +        guideItems.add(new UserGuideItem("find", "Find contacts with a keyword.\n"
```suggestion
        guideItems.add(new UserGuideItem("find", "Find contacts whose names contain any of the given keywords.\n"
```

2024-03-18 09:42 UTC, Tanzhiheng26 approved these changes
LGTM

2024-03-19 04:14 UTC, ziiqii reviewed
Overall help window looks good, I've left some comments on areas that need fixing.

Some comments for your consideration (for future iterations):
1. Could potentially remove sorting from the 'Usage' header in the help window, as users don't usually sort using that field.
2. The default order of commands shown initially (help -> add -> list...) becomes inaccessible once the user sorts the commands, perhaps we could restore it, as the default order corresponds to the order of features in the UG.
3. Could consider styling parts of the command usage with markdown, similar to our UG, improving readability.

2024-03-19 04:14 UTC, ziiqii commented on src/main/java/seedu/address/ui/HelpWindow.java
> +            + "\n\nThings to note:"
Could be useful to inform users of the sort function in the help window

2024-03-19 09:55 UTC, ziiqii approved these changes
LGTM!

2024-03-19 09:55 UTC, merged